# Generated by Django 3.2.9 on 2021-12-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicepscurl',
            name='total_time',
        ),
    ]
