# Generated by Django 3.2.9 on 2021-12-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BicepsCurl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20)),
                ('Lcount', models.CharField(max_length=20)),
                ('Rcount', models.CharField(max_length=20)),
                ('times', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PushUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20)),
                ('total_time', models.CharField(max_length=20)),
                ('count', models.IntegerField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Squat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20)),
                ('total_time', models.CharField(max_length=20)),
                ('count', models.IntegerField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='pid',
            field=models.CharField(max_length=20),
        ),
    ]
