# Generated by Django 3.2.9 on 2021-12-03 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20211202_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squat',
            options={},
        ),
        migrations.RenameField(
            model_name='bicepscurl',
            old_name='Lcount',
            new_name='count1',
        ),
        migrations.RenameField(
            model_name='bicepscurl',
            old_name='Rcount',
            new_name='count2',
        ),
        migrations.RemoveField(
            model_name='squat',
            name='created',
        ),
    ]
