# Generated by Django 3.2.9 on 2021-12-03 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20211203_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bicepscurl',
            old_name='count1',
            new_name='count',
        ),
    ]
