# Generated by Django 3.2.9 on 2021-12-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_rename_count1_bicepscurl_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicepscurl',
            name='count',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bicepscurl',
            name='count2',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bicepscurl',
            name='day',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bicepscurl',
            name='pid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bicepscurl',
            name='times',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bicepscurl',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pushup',
            name='count',
            field=models.CharField(max_length=10),
        ),
    ]
