# Generated by Django 3.2.9 on 2021-12-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20211206_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='nick_name',
        ),
    ]
