# Generated by Django 3.2.9 on 2021-12-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_remove_account_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pwd',
            field=models.CharField(max_length=255),
        ),
    ]
