# Generated by Django 3.2.9 on 2021-12-20 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0008_remove_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='highlighted',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
