# Generated by Django 3.2.9 on 2021-12-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_auto_20211220_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='push',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('times', models.FloatField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('day', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
