# Generated by Django 3.2.9 on 2021-12-19 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_auto_20211218_0552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cover',
        ),
    ]
