# Generated by Django 4.0 on 2021-12-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicepscurl',
            name='sum_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bicepscurl',
            name='sum_times',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bicepscurl',
            name='day',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bicepscurl',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
