# Generated by Django 4.0 on 2021-12-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_pushup_sum_count_pushup_sum_times_squat_sum_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushup',
            name='day',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pushup',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='squat',
            name='day',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='squat',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
